# Generated by Django 5.1.4 on 2025-01-02 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rarity', models.CharField(choices=[('C', 'Common'), ('R', 'Rare'), ('RR', 'Double Rare'), ('RRR', 'Triple Rare'), ('SP', 'Special')], max_length=10)),
                ('set_code', models.CharField(max_length=10)),
            ],
        ),
    ]
