# Generated by Django 5.1.4 on 2025-01-06 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cards',
        ),
    ]
