# Generated by Django 5.1.4 on 2025-01-06 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_remove_userprofile_cards'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.cards')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cards',
            field=models.ManyToManyField(related_name='owners', through='game.UserCard', to='game.cards'),
        ),
    ]
