# Generated by Django 5.1.4 on 2025-01-13 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_card_alter_usercard_card_alter_userprofile_cards_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdeck',
            name='highlight_card_image',
            field=models.CharField(default='https://i.imgur.com/vJmy5qL.png', max_length=255, null=True),
        ),
    ]
